<?php

/*
 * This file is part of the Symfony package.
 * (c) Stéphane BRIERE <stephanebriere@gdpweb.fr>
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AppBundle\Repository;

/**
 * UserRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $token
     *
     * @throws \Doctrine\ORM\NonUniqueResultException
     *
     * @return mixed
     */
    public function tokenIsValid($token)
    {
        $date = new \DateTime('NOW -20 minutes', new \DateTimezone('Europe/Paris'));

        return $this->createQueryBuilder('a')
            ->where('a.dateToken >= :date')
            ->andWhere('a.token = :token')
            ->setParameter('date', $date)
            ->setParameter('token', $token)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
